2018-12-04 11:06:10,602 ERROR: Exception on /explore [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/routes.py", line 224, in explore
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2018-12-04 11:06:12,197 ERROR: Exception on /explore [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/routes.py", line 224, in explore
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2018-12-04 11:06:12,834 ERROR: Exception on /welcome [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/routes.py", line 93, in welcome
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2018-12-04 11:09:05,400 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:54]
2018-12-04 11:09:52,617 ERROR: Exception on /welcome [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/routes.py", line 93, in welcome
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2018-12-04 11:10:33,818 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:54]
2018-12-04 11:50:08,070 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:54]
2018-12-04 15:00:49,712 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:54]
2018-12-05 14:47:25,689 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:59]
2018-12-05 14:48:14,916 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:59]
2018-12-05 14:49:14,962 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:59]
2018-12-05 14:49:27,640 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:59]
2018-12-05 14:52:26,732 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:59]
2018-12-05 17:33:06,900 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:59]
2018-12-05 17:39:00,627 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:59]
2018-12-05 17:40:56,509 INFO: Microblog startup [in /Users/xinyaotian/Code/Python_Codes/flask_learning/microblog/app/__init__.py:59]
